import type { InventoryItem } from "api-contracts";

export const portfolioInventory: Record<string, InventoryItem[]> = {
  account1: [
    { hashName: "Sticker | Fnatic (Gold) | 2020 RMR", quantity: 332 },
    { hashName: "Berlin 2019 Minor Challengers Autograph Capsule", quantity: 600 },
    { hashName: "Berlin 2019 Returning Challengers Autograph Capsule", quantity: 200 },
    { hashName: "Berlin 2019 Legends Autograph Capsule", quantity: 200 },
    { hashName: "2020 RMR Contenders", quantity: 1000 },
    { hashName: "2020 RMR Challengers", quantity: 1000 },
    { hashName: "2020 RMR Legends", quantity: 1000 },
    { hashName: "Stockholm 2021 Challengers Sticker Capsule", quantity: 500 },
    { hashName: "Stockholm 2021 Legends Sticker Capsule", quantity: 500 },
    { hashName: "Stockholm 2021 Champions Autograph Capsule", quantity: 500 },
    { hashName: "Antwerp 2022 Champions Autograph Capsule", quantity: 500 },
    { hashName: "Antwerp 2022 Legends Sticker Capsule", quantity: 500 },
    { hashName: "Antwerp 2022 Legends Autograph Capsule", quantity: 500 },
    { hashName: "Rio 2022 Challengers Autograph Capsule", quantity: 1000 },
    { hashName: "Rio 2022 Challengers Sticker Capsule", quantity: 1000 },
    { hashName: "Rio 2022 Champions Autograph Capsule", quantity: 1000 },
    { hashName: "Paris 2023 Challengers Autograph Capsule", quantity: 1000 },
    { hashName: "Paris 2023 Challengers Sticker Capsule", quantity: 1000 },
    { hashName: "Austin 2025 Legends Sticker Capsule", quantity: 500 },
    { hashName: "Austin 2025 Legends Autograph Capsule", quantity: 500 },
    { hashName: "Sticker | 100 Thieves (Gold) | 2020 RMR", quantity: 207 },
    { hashName: "Sticker | TYLOO (Gold) | 2020 RMR", quantity: 30 },
    { hashName: "Sticker | Renegades (Gold) | 2020 RMR", quantity: 10 },
    { hashName: "Sticker | Boom (Gold) | 2020 RMR", quantity: 10 },
    { hashName: "Sticker | North (Gold) | 2020 RMR", quantity: 1 },
    { hashName: "Sticker | fitch (Gold) | Katowice 2019", quantity: 1 },
    { hashName: "Sticker | dephh (Gold) | Berlin 2019", quantity: 1 },
    { hashName: "Sticker | SicK (Gold) | Berlin 2019", quantity: 1 },
    { hashName: "Sticker | yel (Gold) | Berlin 2019", quantity: 1 },
    { hashName: "Sticker | AZR (Gold) | Berlin 2019", quantity: 2 },
    { hashName: "Sticker | Gratisfaction (Gold) | Berlin 2019", quantity: 3 },
    { hashName: "Sticker | GeT_RiGhT (Gold) | Berlin 2019", quantity: 12 },
    { hashName: "Sticker | olofmeister (Gold) | Berlin 2019", quantity: 1 },
    { hashName: "Sticker | KRIMZ (Gold) | Katowice 2019", quantity: 1 },
    { hashName: "Sticker | Rickeh (Gold) | Berlin 2019", quantity: 7 },
    { hashName: "'The Doctor' Romanov | Sabre", quantity: 1 },
    { hashName: "'Two Times' McCoy | USAF TACP", quantity: 1 },
    { hashName: "AK-47 | Emerald Pinstripe (Well-Worn)", quantity: 1 },
    { hashName: "AK-47 | Fuel Injector (Minimal Wear)", quantity: 1 },
    { hashName: "AK-47 | Legion of Anubis (Minimal Wear)", quantity: 1 },
    { hashName: "AK-47 | Slate (Minimal Wear)", quantity: 1 },
    { hashName: "AK-47 | Uncharted (Minimal Wear)", quantity: 1 },
    { hashName: "AWP | Mortis (Field-Tested)", quantity: 1 },
    { hashName: "Chef d'Escadron Rouchard | Gendarmerie Nationale", quantity: 1 },
    { hashName: "Cmdr. Mae 'Dead Cold' Jamison | SWAT", quantity: 1 },
    { hashName: "Desert Eagle | Crimson Web (Minimal Wear)", quantity: 1 },
    { hashName: "M4A4 | Buzz Kill (Minimal Wear)", quantity: 1 },
    { hashName: "M4A4 | Magnesium (Field-Tested)", quantity: 1 },
    { hashName: "Music Kit | Austin Wintory, Bachram", quantity: 1 },
    { hashName: "Music Kit | Ki:Theory, MOLOTOV", quantity: 1 },
    { hashName: "Sir Bloody Skullhead Darryl | The Professionals", quantity: 1 },
    { hashName: "StatTrak™ AK-47 | Elite Build (Minimal Wear)", quantity: 1 },
    { hashName: "Vypa Sista of the Revolution | Guerrilla Warfare", quantity: 1 },
  ],
  account2: [
    { hashName: "Austin 2025 Challengers Autograph Capsule", quantity: 500 },
    { hashName: "Austin 2025 Challengers Sticker Capsule", quantity: 500 },
    { hashName: "Paris 2023 Contenders Sticker Capsule", quantity: 1000 },
    { hashName: "Paris 2023 Contenders Autograph Capsule", quantity: 1000 },
    { hashName: "Rio 2022 Contenders Autograph Capsule", quantity: 1000 },
    { hashName: "Rio 2022 Contenders Sticker Capsule", quantity: 1000 },
    { hashName: "Antwerp 2022 Challengers Sticker Capsule", quantity: 500 },
    { hashName: "Antwerp 2022 Challengers Autograph Capsule", quantity: 500 },
    { hashName: "Stockholm 2021 Finalists Autograph Capsule", quantity: 1000 },
    { hashName: "2020 RMR Contenders", quantity: 1000 },
    { hashName: "2020 RMR Challengers", quantity: 1000 },
    { hashName: "2020 RMR Legends", quantity: 1000 },
    { hashName: "Prisma 2 Case", quantity: 2500 },
    { hashName: "Prisma Case", quantity: 2500 },
  ],
  account3: [
    { hashName: "Austin 2025 Contenders Autograph Capsule", quantity: 500 },
    { hashName: "Austin 2025 Contenders Sticker Capsule", quantity: 500 },
    { hashName: "Paris 2023 Legends Sticker Capsule", quantity: 1000 },
    { hashName: "Paris 2023 Legends Autograph Capsule", quantity: 1000 },
    { hashName: "Rio 2022 Legends Autograph Capsule", quantity: 500 },
    { hashName: "Rio 2022 Legends Sticker Capsule", quantity: 500 },
    { hashName: "Antwerp 2022 Contenders Sticker Capsule", quantity: 500 },
    { hashName: "Antwerp 2022 Contenders Autograph Capsule", quantity: 500 },
    { hashName: "Sticker | Spirit | 2020 RMR", quantity: 1000 },
    { hashName: "Sticker | G2 | 2020 RMR", quantity: 1000 },
    { hashName: "Sticker | FURIA | 2020 RMR", quantity: 1000 },
    { hashName: "Sticker | Nemiga | 2020 RMR", quantity: 1000 },
    { hashName: "Sticker | BIG | 2020 RMR", quantity: 1000 },
    { hashName: "Sticker | Boom | 2020 RMR", quantity: 1000 },
    { hashName: "Sticker | TYLOO | 2020 RMR", quantity: 1000 },
    { hashName: "Sticker | ESPADA | 2020 RMR", quantity: 1000 },
    { hashName: "Sticker | Heroic | 2020 RMR", quantity: 1000 },
    { hashName: "Sticker | North | 2020 RMR", quantity: 1000 },
    { hashName: "Sticker | Renegades | 2020 RMR", quantity: 1000 },
    { hashName: "Sticker | Fnatic | 2020 RMR", quantity: 2000 },
    { hashName: "Sticker | Vitality | 2020 RMR", quantity: 1000 },
  ],
  account4: [
    { hashName: "Austin 2025 Champions Autograph Capsule", quantity: 1000 },
    { hashName: "Paris 2023 Champions Autograph Capsule", quantity: 1000 },
  ],
};
